### ISSUE TITLE
Error on install/setup

### ISSUE THREAD

**Issue by Ehesp** [binggg/react-native-material-design-components#11]
With a fresh install, I get the following error when following the instructions to install.

![image](https://cloud.githubusercontent.com/assets/842078/11513809/19c4b426-986d-11e5-926c-c6825fb5c267.png)

Using the latest version of the react-native cli tool.

I also get the logs:

W/ReactNativeJS( 1965): 'Warning: Native component for "RCTModalHostView" does not exist'
W/ReactNativeJS( 1965): '`ProgressBarAndroid` has no propType for native prop `AndroidProgressBar.indeterminate` of native type `boolean`'

**Comment by binggg** [comment]
Sorry, React Native 0.16.0-rc isn't supporting for now.

**Comment by andycaramba** [comment]
Hi. I have the same issue on React Native v0.13.2. After I've created new React Native project all works fine, but when I've modified code according to instructions in [MRN Installation Manual](http://mrn.js.org/manual/installation.html) (without any other modifications in index.android.js and so on), I got this error.

**Comment by binggg** [comment]
@andycaramba Thank you for your reporting. I will check later

**Comment by binggg** [comment]
@Ehesp  
1.Warning: Native component for "RCTModalHostView" does not exist 
See
http://facebook.github.io/react-native/docs/known-issues.html#views

**Comment by andycaramba** [comment]
I've found the solution. In [MRN Installation Manual](http://mrn.js.org/manual/installation.html) command `npm install react-native-vector-icons --save` installs react-native-vector-icons v1.0.0 that has some changes in its [installation instruction](https://github.com/oblador/react-native-vector-icons#android). Particularly folder name `android/app/src/main/assets/fonts` must be in lowercase. Installing react-native-vector-icons v0.8.5 or following updated instructions solves the issue.

**Comment by binggg** [comment]
@andycaramba  Good job! Thanks. Let me update the manual.

**Comment by Ehesp** [comment]
Changing the `Fonts` directory to `fonts` worked for me :) also downgraded to 0.15.\* and it's back working. Thanks for the help @andycaramba

**Comment by christopherdro** [comment]
This is fixed in the stable release of 0.16.
