### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by geezmo** [binggg/react-native-material-design-components#2]
Hello, and thanks for your work - your module looks very promising!
A couple of issues i've been running into (react-native 0.15)

1) I wasn't able to install the module with 

```
npm install react-native-material-design-components
```

as stated in the manual. It seems that the module is registered as "mrn":

```
npm install mrn
```

2) Installing the module with the command above, and requiring it with 

```
var mD = require('mrn');
```

i have the following error:

```
lib/Button.js: Unexpected token (50:24)
```

Am i missing something?

**Comment by binggg** [comment]
Thank you for your reporting.

The truth is I forget to update the manual and forget a .babelrc file.

**Comment by geezmo** [comment]
My fault for not having thought about a .babelrc :-)
