### ISSUE TITLE
Errors after upgrading

### ISSUE THREAD

**Issue by mrcasals** [binggg/react-native-material-design-components#24]
I upgraded from React Native v0.14 to React Native v0.16, and I got some Babel errors:

```
Unknown option: node_modules/mrn/.babelrc.whitelist
```

If I delete this file, I get to compile the project. Any idea what's the issue here?

I'm using MRN @ master.

**Comment by Ehesp** [comment]
Currently in the process of cleaning this all up, but the issue is React Native 0.16 is using babel 6 which doesn't support whitelists - and the index file needs an update to use es6 exports.

**Comment by mrcasals** [comment]
Awesome, thanks! I'll wait until this is fixed to update, than. :)

**Comment by mebibou** [comment]
Any timeline for this to be fixed? I guess many people like me don't want to downgrade React Native to use this awesome library :)

**Comment by Ehesp** [comment]
@mebibou >>> https://github.com/react-native-material-design/react-native-material-design

**Comment by mebibou** [comment]
@Ehesp nice :)
