### ISSUE TITLE
Merge this project with material-ui?

### ISSUE THREAD

**Issue by oliviertassinari** [binggg/react-native-material-design-components#26]
Hi @binggg,

Lately, we have been talking about how to build a cross platform material implementation.
At first, I though that the best way to do it was to create a thrid repository to write wrapper components (abstract API differences).
However, now I'm convinced that it's better to have the different implementation in the same repository (always sync API and potentially shared code).

We have been doing a lot of changes in the material-ui repository recently.
I believe that we now have the needed infrastructures to start working on react-native:
https://github.com/callemall/material-ui/pull/2667

So here is my question, would merging this project back to material-ui makes sense to you?
If not, how do you think that the cross platform common API should be done?

@Ehesp I see that you have started working on https://github.com/react-native-material-design/react-native-material-design. Any insight would be valuable too.

**Comment by Ehesp** [comment]
Hello

As much as I think this would be awesome, I'm unsure how the bridge between the web and the devices would be made. RN uses it's own version of Flexbox, whilst as far as I can see (please correct me) doesn't use Flexbox all over.

Obviously there's loads of difference between the two, which I'm not sure a common API would be good for (Animations, pure native components). Also RN has Android specific components to deal with things such as Rippling etc, how would that translate to iOS?

Happy to talk on my side though... For me it's more a case of having something solid to use and support over individual projects.

**Comment by oliviertassinari** [comment]
> I'm unsure how the bridge between the web and the devices would be made.

For now, I don't plan to share any code between the different implementation.

> how would that translate to iOS?

I'm not sure than iOS should be supported.

> Obviously there's loads of difference between the two, which I'm not sure a common API would be good for (Animations, pure native components)

I'm not sure to follow, do you have an example.

> For me it's more a case of having something solid to use and support over individual projects.

Well, I'm by case, I'm writing an Android / Web app. I want to share as many code as possible between the two platforms.
I don't necessarily want to write the same code.
But as it's stated by react, I want to learn once the material API (that will obviously have some differences between platform) and write anywhere with the minimum overload.

The project seems no longer maintained.
@Ehesp I don't want to redo the wheel, to beging with, I'm gonna try to integrate https://github.com/react-native-material-design/react-native-material-design and see how it goes.

**Comment by Ehesp** [comment]
Right okay, I thought you were on about using the styles from Material-UI directly into React Native.

Well the way I would see this working:
- Having two separate 'sections' on the website, something like:
  http://www.material-ui.com/#/components/buttons & http://www.material-ui.com/#/native-components/buttons
- For each component which is relevant to React Native, follow the same PropTypes as defined on each component (where applicable). Problem here is that some current ones don't apply to ReactJS (such as `iconClassName` on the buttons).
- Some things are not yet possible (such as `Menus`).
- Some components are not needed as specific components (such as `LeftNav`, since we already have the Drawer Android component.

**Comment by oliviertassinari** [comment]
@Ehesp Thank for the tips.
