### ISSUE TITLE
Possablity of an Demo APK

### ISSUE THREAD

**Issue by torbjorn-kvist** [binggg/react-native-material-design-components#3]
Is there any plan on including an apk on the repository/download link in the description, for some fast testing? 

For those who aren't at their development station or just want to see what react native can do with "mrn"?

**Comment by mrcasals** [comment]
In the docs there's an emulator to test what you can do with this library. Source code for the emulator is this React Native app here: https://github.com/binggg/MaterialReactNative

**Comment by binggg** [comment]
Ok, you got it.

**Comment by binggg** [comment]
See README.md
