### ISSUE TITLE
List onPress replaces scroll in a ListView

### ISSUE THREAD

**Issue by mrcasals** [binggg/react-native-material-design-components#4]
When using the `List` component as the row component of a `ListView`, scroll is overwritten by the `onPress` event, so I cannot scroll properly. This is a screenshot of the emulator in the docs:

![](https://i.imgur.com/9xmRr6Q.png)

If the `onPress` event replaces the view, the scroll automatically replaces the view, so scroll is not possible.

**Comment by binggg** [comment]
It's a bug. I will fix it later.
