### ISSUE TITLE
Provide fallback monospace font

### ISSUE THREAD

**Issue by GrilloPress** [binggg/react-native-material-design-components#7]
When I visit the [mrn.js.org](mrn.js.org) website the code examples render in my browsers' generic serif font and not "Source Code Pro". It looks like:

![checkbox_serif_fonts](https://cloud.githubusercontent.com/assets/5756226/11444087/948b826c-951a-11e5-8bfd-dc15ac0c3f40.PNG)

Having a quick look through your CSS I can't see the font being loaded in. Only the Roboto webfont. No errors popup in the browser console either.

Beyond that worth backing up "Source Code Pro" with a reference to the monospace font-family in your CSS

```
pre.prettyprint, pre > code {
   font-family: "Source Code Pro", monospace;
}
```

etc.

**Comment by binggg** [comment]
Fix it. Thank you very much.
